build: off
environment:

  matrix:
    - PLATFORMIO_PROJECT_DIR: "examples/coremark"
    - PLATFORMIO_PROJECT_DIR: "examples/dhrystone"
    - PLATFORMIO_PROJECT_DIR: "examples/whetstone"
    - PLATFORMIO_PROJECT_DIR: "examples/helloworld"
    - PLATFORMIO_PROJECT_DIR: "examples/demo_eclic"
    - PLATFORMIO_PROJECT_DIR: "examples/demo_timer"
    - PLATFORMIO_PROJECT_DIR: "examples/demo_dsp"
    - PLATFORMIO_PROJECT_DIR: "examples/freertos_demo"
    - PLATFORMIO_PROJECT_DIR: "examples/ucosii_demo"

install:
- cmd: git submodule update --init --recursive
- cmd: SET PATH=C:\Python36\Scripts;%PATH%
- cmd: pip install -U https://github.com/platformio/platformio/archive/develop.zip
- cmd: platformio platform install file://.

test_script:
- cmd: platformio run -d %PLATFORMIO_PROJECT_DIR%
