name: Build Examples

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install -U https://github.com/platformio/platformio/archive/develop.zip
          pip install wget

      - name: Caching Nuclei Tools
        uses: actions/cache@v3
        with:
          path: prebuilt_dlcache
          key: build

      - name: Install Nuclei Tools and PIO Packages
        run: |
          python3 .github/prepare_tools.py

      - name: Upload cached packages
        uses: actions/upload-artifact@v3
        with:
          name: prebuilt_caching
          path: |
            prebuilt_dlcache

      - name: Build examples
        run: |
          python3 .github/build_examples.py